<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DisableReasonSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('disable_reasons')->truncate();
        DB::table('disable_reasons')->insert([
            [
                'id' => 1,
                'tenant_id' => 'default',
                'SchoolId' => 0,
                'IsActive' => 1,
                'CreatedBy' => 1,
                'CreatedDate' => Carbon::parse('2021-08-30 19:03:14.493099'),
                'ModifiedBy' => null,
                'ModifiedDate' => null,
                'SessionId' => 1,
                'DisableReasonName' => 'Fee Not Paid',
                'DisableReasonGroupId' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 2,
                'tenant_id' => 'default',
                'SchoolId' => 0,
                'IsActive' => 1,
                'CreatedBy' => 1,
                'CreatedDate' => Carbon::parse('2021-08-31 16:24:38.660901'),
                'ModifiedBy' => null,
                'ModifiedDate' => null,
                'SessionId' => 1,
                'DisableReasonName' => 'leaving for abroad',
                'DisableReasonGroupId' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 3,
                'tenant_id' => 'default',
                'SchoolId' => 0,
                'IsActive' => 1,
                'CreatedBy' => 1,
                'CreatedDate' => Carbon::parse('2021-08-31 16:24:38.660901'),
                'ModifiedBy' => null,
                'ModifiedDate' => null,
                'SessionId' => 1,
                'DisableReasonName' => 'Shifting to Another City',
                'DisableReasonGroupId' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 4,
                'tenant_id' => 'default',
                'SchoolId' => 0,
                'IsActive' => 1,
                'CreatedBy' => 1,
                'CreatedDate' => Carbon::parse('2021-08-31 16:24:38.660901'),
                'ModifiedBy' => null,
                'ModifiedDate' => null,
                'SessionId' => 1,
                'DisableReasonName' => 'Shifting to Another School',
                'DisableReasonGroupId' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 5,
                'tenant_id' => 'default',
                'SchoolId' => 0,
                'IsActive' => 1,
                'CreatedBy' => 1,
                'CreatedDate' => Carbon::parse('2021-08-31 16:24:38.660901'),
                'ModifiedBy' => null,
                'ModifiedDate' => null,
                'SessionId' => 1,
                'DisableReasonName' => 'Parents not Satisfied with School',
                'DisableReasonGroupId' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 6,
                'tenant_id' => 'default',
                'SchoolId' => 0,
                'IsActive' => 1,
                'CreatedBy' => 1,
                'CreatedDate' => Carbon::parse('2021-08-31 16:24:38.660901'),
                'ModifiedBy' => null,
                'ModifiedDate' => null,
                'SessionId' => 1,
                'DisableReasonName' => 'Defaulter',
                'DisableReasonGroupId' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 7,
                'tenant_id' => 'default',
                'SchoolId' => 0,
                'IsActive' => 1,
                'CreatedBy' => 1,
                'CreatedDate' => Carbon::parse('2021-08-31 16:24:38.660901'),
                'ModifiedBy' => null,
                'ModifiedDate' => null,
                'SessionId' => 1,
                'DisableReasonName' => 'Parents Not Responding',
                'DisableReasonGroupId' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 8,
                'tenant_id' => 'default',
                'SchoolId' => 0,
                'IsActive' => 1,
                'CreatedBy' => 1,
                'CreatedDate' => Carbon::parse('2021-08-31 16:24:38.660901'),
                'ModifiedBy' => null,
                'ModifiedDate' => null,
                'SessionId' => 1,
                'DisableReasonName' => 'Matric Student Alumni',
                'DisableReasonGroupId' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 9,
                'tenant_id' => 'default',
                'SchoolId' => 0,
                'IsActive' => 1,
                'CreatedBy' => 1,
                'CreatedDate' => Carbon::parse('2021-08-31 16:24:38.660901'),
                'ModifiedBy' => null,
                'ModifiedDate' => null,
                'SessionId' => 1,
                'DisableReasonName' => 'Double Entry',
                'DisableReasonGroupId' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 10,
                'tenant_id' => 'default',
                'SchoolId' => 0,
                'IsActive' => 1,
                'CreatedBy' => 1,
                'CreatedDate' => Carbon::parse('2021-08-31 16:24:38.660901'),
                'ModifiedBy' => null,
                'ModifiedDate' => null,
                'SessionId' => 1,
                'DisableReasonName' => 'Dummy Entry',
                'DisableReasonGroupId' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 11,
                'tenant_id' => 'default',
                'SchoolId' => 0,
                'IsActive' => 1,
                'CreatedBy' => 1,
                'CreatedDate' => Carbon::parse('2021-08-31 16:24:38.660901'),
                'ModifiedBy' => null,
                'ModifiedDate' => null,
                'SessionId' => 1,
                'DisableReasonName' => 'Parents not Satisfied with Brand',
                'DisableReasonGroupId' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 12,
                'tenant_id' => 'default',
                'SchoolId' => 0,
                'IsActive' => 1,
                'CreatedBy' => 1,
                'CreatedDate' => Carbon::parse('2021-08-31 16:24:38.660901'),
                'ModifiedBy' => null,
                'ModifiedDate' => null,
                'SessionId' => 1,
                'DisableReasonName' => 'Shifted to Govt. School',
                'DisableReasonGroupId' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
            [
                'id' => 13,
                'tenant_id' => 'default',
                'SchoolId' => 0,
                'IsActive' => 0,
                'CreatedBy' => 1,
                'CreatedDate' => Carbon::now(),
                'ModifiedBy' => null,
                'ModifiedDate' => null,
                'SessionId' => 1,
                'DisableReasonName' => 'Withdraw',
                'DisableReasonGroupId' => 1,
                'created_at' => now(),
                'updated_at' => now(),
                'deleted_at' => null,
            ],
        ]);
    }
}
